# Generated by Django 3.2.6 on 2021-11-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contacts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='date',
        ),
    ]
